### ISSUE TITLE
Support for Multi-conformer PDB input

### ISSUE THREAD

**Issue by picodase** [jr-marchand/caviar#2]
Hello,

This software is great! It is fast and does precisely what I want it to do. I am interested in using it for analyzing voids and cavities in molecular dynamics simulations (PDB files with many conformers, similar to NMR structures) but with an initial attempt, it seems to only calculate the cavities for the first PDB structure. I understand this would take multiplicatively longer to process the number of frames, but this would be quite useful!

Regards,
Jacob

**Comment by jr-marchand** [comment]
Hi Jacob,
thanks for the nice feedback! The paper should be out soon with details about the software.

Indeed, for now, the package is targeting single PDB structures (basically static X-ray conformations). Although parsing frames from NMR/MD is in the back of my mind for the mid-term development, I don't plan to implement it in the near future (it is time consuming...). I would recommend, as of now, to split the trajectories into multiple PDB files. You can input a list of PDB files with the _codeslist_ option, documented in [link](https://jr-marchand.github.io/caviar/advanced-use/configuration#input), and [tutorial](https://jr-marchand.github.io/caviar/using-caviar/caviar-cmdline).

For an MD simulation, it would simplify the task to align/cluster/extract cluster representatives(/metastable states) as separate PDBs and run CAVIAR on them. You would have to quantify the change/evolution of your pockets of interest yourself. Depending on what you want to do, a quick and dirty solution to track a cavity could probably be to follow the evolution of the size/buriedness/hydrophobicity(/ligandability) descriptors. The code for cavity comparison in CAVIAR is work in progress :).

Cheers,
JR

**Comment by jr-marchand** [comment]
Hey Jacob, just to let you know I've updated the code.
Now, you can parse MD trajectories as DCD file format,, as well as different models in an NMR PDB file (and I also implemented an mmCIF parser).
Check out the new post on the website: https://jr-marchand.github.io/caviar/advanced-use/cif-dcd-nmr

If you want a bit more details on the methodology, I have uploaded a draft on ChemXriv: https://dx.doi.org/10.26434/chemrxiv.12806819
